# Generated by Django 4.2.16 on 2024-11-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('anuncios', 'crear_tipoanuncio'),
        ('anuncios', '0002_anuncio_tipo'),
    ]

    operations = [
    ]
