# Generated by Django 4.2.16 on 2024-11-02 16:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_merge_0002_anuncio_tipo_crear_tipoanuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to=''),
        ),
    ]
